jobs:
  - name: job11
    type: manifest
    steps:
      - GET: image1-test
      - GET: image2-test
      - GET: s16
      - PUT: s3
      - PUT: s4
     # - PUT: image3-test

  - name: job12
    type: manifest
    steps:
      - GET: project1-test
      - GET: s1
      - GET: s2
      - PUT: image1-test
      - PUT: image2-test
      - PUT: s15
      - PUT: s16
      - PUT: job11
      

  - name: job13
    type: manifest
    steps:
      - GET: image1-test
      - GET: s15
      - GET: s16
      - PUT: s5
  
  - name: job14
    type: ecsDeploy
    steps:
      - GET: s6
      - GET: project1-test
      - PUT: s7
      - PUT: image1-test
      
      
      
      
